# Build stage
FROM gradle:jdk8 AS build
WORKDIR /app
COPY . .
RUN gradle build -x test

# Run stage
FROM openjdk:8-jre
COPY --from=build /app/build/libs/producer-*.jar /producer.jar
ENTRYPOINT ["java", "-jar", "/producer.jar"]